name: project_1
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  page_transition: ^2.0.2
  font_awesome_flutter: ^9.0.0
  image_picker: ^0.7.5
  flutter_animated_dialog: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/
  

  
  

  
  

  
  
  
  
  
  fonts:
    - family: Bison
      fonts:
        - asset: fonts/Bison-Bold.ttf
       
    - family: OP_R
      fonts:
        - asset: fonts/OpenSans-Regular.ttf

    - family: OP_L
      fonts:
        - asset: fonts/OpenSans-Light.ttf

    - family: OP_S
      fonts:
        - asset: fonts/OpenSans-SemiBold.ttf

    - family: OP_B
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
  
  
  
  
  
