import 'package:project_1/model/car.dart';

class CarRepo {
  List<Car> topCars = [
    Car(
      name: 'X6',
      color: 'White',
      maker: 'BMW',
      km: '1000',
      year: '2021',
      price: '\$32000',
      rating: 5,
      imageUrl: 'assets/x6.jpg',
      favorite: false,
    ),
    Car(
      name: 'A4',
      color: 'Silver',
      maker: 'Audi',
      km: '1500',
      year: '2020',
      price: '\$28000',
      rating: 4,
      imageUrl: 'assets/a4.jpg',
      favorite: false,
    ),
    Car(
      name: 'Highlander',
      color: 'Silver',
      maker: 'Toyota',
      km: '2000',
      year: '2020',
      price: '\$18000',
      rating: 4,
      imageUrl: 'assets/highlander.jpg',
      favorite: false,
    ),
    Car(
      name: 'Camry',
      color: 'Brown',
      maker: 'Toyota',
      km: '10000',
      year: '2018',
      price: '\$10000',
      rating: 3,
      imageUrl: 'assets/camry.jpg',
      favorite: false,
    ),
    Car(
      name: 'CR-V',
      color: 'Blue',
      maker: 'Honda',
      km: '6000',
      year: '2020',
      price: '\$16000',
      rating: 4,
      imageUrl: 'assets/crv.jpg',
      favorite: false,
    ),
  ];
  List<Car> cars = [
    Car(
      name: 'Corolla X',
      color: 'White',
      maker: 'Toyota',
      km: '5000',
      year: '2020',
      price: '\$8500',
      rating: 4,
      imageUrl: 'assets/corolla_x.jpg',
      favorite: false,
    ),
    Car(
      name: 'Camry',
      color: 'Brown',
      maker: 'Toyota',
      km: '10000',
      year: '2018',
      price: '\$10000',
      rating: 3,
      imageUrl: 'assets/camry.jpg',
      favorite: false,
    ),
    Car(
      name: 'Accord',
      color: 'Red',
      maker: 'Honda',
      km: '6000',
      year: '2020',
      price: '\$12000',
      rating: 4,
      imageUrl: 'assets/accord.jpg',
      favorite: false,
    ),
    Car(
      name: 'CR-V',
      color: 'Blue',
      maker: 'Honda',
      km: '6000',
      year: '2020',
      price: '\$16000',
      rating: 4,
      imageUrl: 'assets/crv.jpg',
      favorite: false,
    ),
    Car(
      name: 'Civic',
      color: 'Black',
      maker: 'Honda',
      km: '4000',
      year: '2020',
      price: '\$18000',
      rating: 4,
      imageUrl: 'assets/honda_civic.jpg',
      favorite: false,
    ),
  ];
}
